version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    build:
      context: .
      dockerfile: ./cmd/server/product/Dockerfile
    container_name: product-service
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: edot_product
    ports:
      - "8081:8081"
    networks:
      - edot-net

  order-service:
    build:
      context: .
      dockerfile: ./cmd/server/order/Dockerfile
    container_name: order-service
    depends_on:
      - mysql
      - product-service
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ecommerce
      PRODUCT_SERVICE_URL: http://product-service:8081/api/v1
      PRODUCT_SERVICE_API_KEY: internal-api-key-change-in-production
    ports:
      - "8082:8082"
    networks:
      - edot-net

  user-service:
    build:
      context: .
      dockerfile: ./cmd/server/user/Dockerfile
    container_name: user-service
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: edot_user
    ports:
      - "8080:8080"
    networks:
      - edot-net

volumes:
  mysql_data:

networks:
  edot-net:
    driver: bridge
